import { motion } from 'framer-motion';

export default function PrivacyPolicy() {
  return (
    <div className="pt-32 pb-24 px-6 lg:px-8 max-w-4xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        status={{ opacity: 1, y: 0 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
      >
        <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900 heading-premium mb-8">
          Privacy Policy
        </h1>
        <p className="text-gray-500 mb-8 font-medium">Last updated: April 10, 2026</p>

        <div className="prose prose-blue max-w-none space-y-10 text-gray-600 font-medium leading-relaxed">
          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">1. Data Collection</h2>
            <p>
              IntervueX is designed with privacy in mind. We do not collect, store, or transmit any of your personal data to external servers. All information you enter into the app stays strictly on your mobile device.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">2. Local Storage Usage</h2>
            <p>
              Your interview details, company notes, and schedules are stored locally using your device's secure storage. We do not have access to this data. If you delete the app, this local data will be removed.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">3. Notifications Usage</h2>
            <p>
              The app uses local notifications to send you interview reminders. These notifications are generated by the app on your device and do not involve any external tracking or remote servers.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">4. Advertising & Third-Party Services</h2>
            <p>
              To keep IntervueX free, we use third-party services for advertising and analytics. 
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-3">
              <li>
                <strong>Google AdMob:</strong> This app uses Google AdMob which may collect device information (such as Advertising IDs) for the purpose of serving personalized or non-personalized advertisements.
              </li>
              <li>
                <strong>Google Ads:</strong> We may use Google Ads services to promote the app. These services use cookies and device identifiers to measure ad performance.
              </li>
            </ul>
            <p className="mt-4">
              For more information on how Google uses data, please visit their <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">Privacy & Terms</a>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">5. Data Sharing</h2>
            <p>
              We do not share your personal information with third parties. The only data processed is by the advertising partners mentioned above for the sole purpose of ad delivery and performance tracking.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">6. Security</h2>
            <p>
              We prioritize the security of your local data. However, as the data is stored on your device, we recommend using device-level security features like biometrics or passcodes to protect your information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 heading-premium mb-4">7. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at:
            </p>
            <p className="mt-4 font-bold text-gray-900">
              Email: <a href="mailto:hello@nopelt.com" className="text-blue-600">hello@nopelt.com</a>
            </p>
            <p className="mt-2">
              Contact us at: hello@nopelt.com
            </p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
